name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'adoptopenjdk'

    - name: Build with Maven
      working-directory: ./java
      run: mvn clean install
